# Generated by Django 4.2.2 on 2025-09-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Введите страну проживания",
                max_length=50,
                null=True,
                verbose_name="Страна",
            ),
        ),
    ]
