# Generated by Django 4.2.2 on 2025-09-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                help_text="Если хотите заблокировать его то уберить галочку",
                verbose_name="Аккаунт пользователя активен",
            ),
        ),
    ]
