# Generated by Django 4.2.2 on 2026-03-13 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Если хотите заблокировать его то уберить галочку",
                verbose_name="Аккаунт пользователя активен",
            ),
        ),
    ]
