# Generated by Django 4.2.2 on 2025-09-10 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["sending_date", "end_date_of_send", "status"],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RenameField(
            model_name="newsletter",
            old_name="end_of_sending",
            new_name="end_date_of_send",
        ),
        migrations.RenameField(
            model_name="newsletter",
            old_name="sending",
            new_name="sending_date",
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(max_length=9, verbose_name="Статус"),
        ),
        migrations.CreateModel(
            name="AttemptToSend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date_of_attempt",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата и время попытки"
                    ),
                ),
                ("status", models.CharField(max_length=10, verbose_name="Статус")),
                (
                    "mail_server_response",
                    models.TextField(verbose_name="Ответ почтового сервера"),
                ),
                (
                    "newsletter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mailings.newsletter",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
                "ordering": ["date_of_attempt", "status"],
            },
        ),
    ]
