# Generated by Django 4.2.2 on 2025-09-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_alter_newsletter_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.TextField(
                help_text="Введите текст письма", verbose_name="Текст письма"
            ),
        ),
    ]
