# Generated by Django 4.2.2 on 2025-09-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_alter_newsletter_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="recipients",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="mailings.mailingrecipient",
                verbose_name="Получатели",
            ),
        ),
    ]
