# Generated by Django 4.2.2 on 2025-09-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0003_alter_message_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="recipients",
            field=models.ManyToManyField(
                to="mailings.mailingrecipient", verbose_name="Получатели"
            ),
        ),
    ]
