# Generated by Django 4.2.2 on 2025-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0004_alter_newsletter_recipients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingrecipient",
            name="comment",
            field=models.TextField(
                help_text="Напишите комментарий", verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="mailingrecipient",
            name="email",
            field=models.CharField(
                help_text="Введите email",
                max_length=150,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="mailingrecipient",
            name="full_name",
            field=models.CharField(
                help_text="Введите Ф.И.О", max_length=150, verbose_name="Ф.И.О"
            ),
        ),
    ]
