# Generated by Django 4.2.2 on 2025-09-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0005_alter_mailingrecipient_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsletter",
            name="end_date_of_send",
            field=models.DateTimeField(
                help_text="Впишите дату и время окончания отправки",
                verbose_name="Дата и время окончания отправки",
            ),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="sending_date",
            field=models.DateTimeField(
                help_text="Впишите дату и время первой отправки",
                verbose_name="Дата и время первой отправки",
            ),
        ),
    ]
