# Generated by Django 4.2.2 on 2025-09-24 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0007_attempttosend_owner_mailingrecipient_owner_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailingrecipient",
            options={
                "ordering": ["email", "full_name"],
                "permissions": [
                    ("can_view_mailing_recipient", "Can view mailing recipient")
                ],
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["sending_date", "end_date_of_send", "status"],
                "permissions": [("can_view_newsletter", "Can view newsletter")],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.RemoveField(
            model_name="attempttosend",
            name="owner",
        ),
    ]
