# Generated by Django 4.2.2 on 2025-09-24 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0009_message_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["topic"],
                "permissions": [("can_view_message", "Can view message")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
