# Generated by Django 4.2.2 on 2025-09-25 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0010_alter_message_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="newsletter_is_disabled",
            field=models.BooleanField(default=False, verbose_name="Рассылка отключена"),
        ),
    ]
