# Generated by Django 4.2.2 on 2025-09-25 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0011_newsletter_newsletter_is_disabled"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsletter",
            options={
                "ordering": ["sending_date", "end_date_of_send", "status"],
                "permissions": [
                    ("can_view_newsletter", "Can view newsletter"),
                    ("can_newsletter_is_disabled", "Can newsletter is disabled"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
    ]
